website/views.py
from flask import Blueprint, render_template, request, flash, redirect, session, url_for, abort
from flask_login import login_required, current_user
from .models import Post, User, Arquivo, ArquivoExcluido, PostExcluido, Mensagem
from . import db
from . import allowed_file
from flask import current_app
from werkzeug.utils import secure_filename
import time 
import base64

views = Blueprint('views', __name__)

TEMPORARY_GARBAGE_TIMEOUT = 3000
BLIP_API_URL = 'https://msging.net/messages'
BLIP_AUTH_KEY = 'your_blip_auth_key'
UPLOAD_FOLDER = '/caminho/para/upload'

@views.route('/', methods=['GET', 'POST'])
# @views.route('/home')
@login_required
def home():
    return render_template('index.html', name=current_user.nome)


@views.route('/auto_message')
def auto_message():
    arquivos = Arquivo.query.all()
    return render_template('auto_message.html', arquivos=arquivos)


@views.route('/help')
def help():
    return render_template('help.html')

@views.route('/comunidade', methods=['GET', 'POST'])
@login_required
def comunidade():
    if request.method == 'POST':
        text = request.form.get('text')
        if not text:
            flash('Postagem não encontrada.', category='error')
        else:
            post = Post(text=text, author=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('Postado com sucesso!', category='sucess')
    posts = Post.query.all()
    return render_template('comunidade.html', posts=posts, user=current_user)



@views.route('/upload', methods=['POST', 'GET'])
def upload_file():
    if 'file' not in request.files:
        flash('Nenhum arquivo selecionado.', category='error')
        return redirect(request.url)

    file = request.files['file']

    if file.filename == '':
        flash('Nenhum arquivo selecionado.', category='error')
        return redirect(request.url)

    allowed_extensions = current_app.config['ALLOWED_EXTENSIONS']  

    if file and allowed_file(file.filename, allowed_extensions):  
        filename = secure_filename(file.filename)
        tipo = filename.rsplit('.', 1)[1].lower()
        conteudo = file.read()

        novo_arquivo = Arquivo(nome=filename, conteudo=conteudo, tipo=tipo, user_id=current_user.id)
        db.session.add(novo_arquivo)
        db.session.commit()

        flash('Arquivo enviado com sucesso!', category='success')
        return redirect(url_for('views.auto_message'))

    flash('Tipo de arquivo não permitido.', category='error')
    return redirect(request.url)


@views.route('/lixo', methods=['GET'])  
def set_temporary_garbage():
    arquivos_excluidos = ArquivoExcluido.query.filter_by(user_id=current_user.id).all()
    posts_excluidos = PostExcluido.query.filter_by(user_id=current_user.id).all()
    garbage_list = []
    for arquivo in arquivos_excluidos:
        garbage_list.append(arquivo)
    for post in posts_excluidos:
        garbage_list.append(post)
    
    return render_template('lixo.html', garbage_list=garbage_list)  

def get_temporary_garbage():
    data = session.get('temporary_garbage')
    if data:
        return data
    else:
        return 'No temporary garbage found'

@views.before_request
def clear_temporary_garbage():
    if 'last_activity' in session and time.time() - session['last_activity'] > TEMPORARY_GARBAGE_TIMEOUT:
        session.pop('temporary_garbage', None)
    session['last_activity'] = time.time()
    
@views.route('/visualizar_arquivo/<int:arquivo_id>')
def visualizar_arquivo(arquivo_id):
    arquivo = Arquivo.query.filter_by(id=arquivo_id).first()
    if arquivo:
        arquivo.conteudo_base64 = base64.b64encode(arquivo.conteudo).decode('utf-8')
        return render_template('visualizar_arquivo.html', arquivo=arquivo)
    else:
        flash('Arquivo não encontrado.', category='error')
        return redirect(url_for('views.auto_message'))


@views.route('/delete_post/<int:id>')
def delete_post(id):
    post = Post.query.get(id)

    if not post:
        flash('Postagem não encontrada.', category='error')
    elif current_user != post.user: 
        flash('Você não tem permissão para excluir esta postagem.', category='error')
    else:
        post_excluido = PostExcluido(text=post.text, user_id=current_user.id)
        db.session.add(post_excluido)
        db.session.delete(post)
        db.session.commit()
        flash('Postagem deletada com sucesso.', category='success')

    return redirect(url_for('views.comunidade'))


@views.route('/apagar_arquivo/<int:id>', methods=['GET', 'POST'])
@views.route('/apagar_arquivo/<int:id>', methods=['POST'])
def delete_arquivo(id):
    arquivo = Arquivo.query.get(id)

    if not arquivo:
        flash('Arquivo não encontrado.', category='error')
    elif current_user.id != arquivo.user_id: 
        flash('Você não tem permissão para excluir este arquivo.', category='error')
    else:
        arquivo_excluido = ArquivoExcluido(nome=arquivo.nome, conteudo=arquivo.conteudo, tipo=arquivo.tipo, user_id=current_user.id)
        db.session.add(arquivo_excluido)
        db.session.delete(arquivo)
        db.session.commit()
        flash('Arquivo excluído com sucesso.', category='success')

    return redirect(url_for('views.auto_message'))


@views.route('/lixo_temporario', methods=['GET', 'POST'])
@login_required
def lixo_temporario():
    if request.method == 'POST':
        selected_item_id = request.form.get('garbage')
        selected_item_type = request.form.get('item_type')

        if selected_item_type == 'arquivo':
            item = ArquivoExcluido.query.filter_by(id=selected_item_id, user_id=current_user.id).first()
        elif selected_item_type == 'postagem':
            item = PostExcluido.query.filter_by(id=selected_item_id, user_id=current_user.id).first()
        else:
            flash('Tipo de item selecionado inválido.', category='error')
            return redirect(url_for('views.lixo_temporario'))

        if item:
            flash(f'Item "{item.nome}" recuperado com sucesso.', category='success')
            # Faça o que precisa ser feito para recuperar o item

    arquivos_excluidos = ArquivoExcluido.query.filter_by(user_id=current_user.id).all()
    posts_excluidos = PostExcluido.query.filter_by(user_id=current_user.id).all()
    return render_template('lixo_temporario.html', arquivos_excluidos=arquivos_excluidos, posts_excluidos=posts_excluidos)

@views.route('/funil', methods=['GET', 'POST'])
@login_required
def funil():
    if request.method == 'POST':
        conteudo = request.form.get('conteudo')
        arquivo_id = request.form.get('arquivo')  

        if 'enviar' in request.form:
            enviar_mensagem(conteudo, arquivo_id)
        elif 'salvar' in request.form:
            salvar_mensagem(conteudo, request.files.get('arquivo'))

    arquivos = current_user.arquivos
    mensagens = Mensagem.query.filter_by(user_id=current_user.id).all()
    return render_template('funil.html', arquivos=arquivos, mensagens=mensagens)


def excluir_mensagem(mensagem_id):
    mensagem = Mensagem.query.get(mensagem_id)

    if mensagem:
        if mensagem.user_id == current_user.id:
            db.session.delete(mensagem)
            db.session.commit()
            flash('Mensagem excluída com sucesso.', category='success')
        else:
            flash('Você não tem permissão para excluir esta mensagem.', category='error')
    else:
        flash('Mensagem não encontrada.', category='error')


def enviar_mensagem(conteudo, arquivo_id):
    # Salvar a mensagem no banco de dados associada ao usuário atual
    nova_mensagem = Mensagem(conteudo=conteudo, user_id=current_user.id, arquivo_id=arquivo_id)
    db.session.add(nova_mensagem)
    db.session.commit()

    # Enviar a mensagem pelo WhatsApp usando a API Blip
    try:
        arquivo = Arquivo.query.filter_by(user_id=current_user.id).all()
        if arquivo:
            media_url = request.url_root + arquivo.caminho
            payload = {
                "to": current_user.telefone,
                "type": "application/json",
                "content": {
                    "type": "text/plain",
                    "text": conteudo,
                    "mediaLink": media_url
                }
            }
        else:
            payload = {
                "to": current_user.telefone,
                "type": "application/json",
                "content": {
                    "type": "text/plain",
                    "text": conteudo
                }
            }

        headers = {
            'Content-Type': 'application/json',
            'Authorization': f'Key {BLIP_API_KEY}'
        }

        response = requests.post('https://msging.net/messages', json=payload, headers=headers)
        if response.status_code == 200:
            flash('Mensagem enviada com sucesso pelo WhatsApp.', category='success')
        else:
            flash('Erro ao enviar mensagem pelo WhatsApp.', category='error')
    except Exception as e:
        flash(f'Erro ao enviar mensagem pelo WhatsApp: {str(e)}', category='error')


def salvar_mensagem(conteudo, arquivo):
    caminho_arquivo = salvar_arquivo(arquivo)
    
    if caminho_arquivo:
        novo_arquivo = Arquivo(
            nome=arquivo.filename,
            caminho=caminho_arquivo,
            user_id=current_user.id
        )
        db.session.add(novo_arquivo)
        db.session.commit()

        nova_mensagem = Mensagem(
            conteudo=conteudo,
            arquivo_id=novo_arquivo.id,
            user_id=current_user.id
        )
        db.session.add(nova_mensagem)
        db.session.commit()
        flash('Mensagem e arquivo salvos com sucesso.', category='success')
    else:
        nova_mensagem = Mensagem(
            conteudo=conteudo,
            user_id=current_user.id
        )
        db.session.add(nova_mensagem)
        db.session.commit()
        flash('Mensagem salva com sucesso.', category='success')

def salvar_arquivo(arquivo):
    if arquivo:

website/templates/auto_message.html
{% extends 'base.html' %}
{% block title %} ZapSelling {% endblock %} 

{% block content %} 
    <h1>Lista de Arquivos</h1>
    <ul>
        {% for arquivo in arquivos %}
            {% if current_user.is_authenticated and arquivo.user_id == current_user.id %}
                <li>
                    <a href="{{ url_for('views.visualizar_arquivo', arquivo_id=arquivo.id) }}">{{ arquivo.nome }}</a>
                    <form action="{{ url_for('views.delete_arquivo', id=arquivo.id) }}" method="post">
                        <button type="submit" class="btn btn-sm btn-danger">Excluir</button>
                    </form>
                </li>
            {% endif %}
        {% endfor %}
    </ul>

    <h1>Upload de Arquivos</h1>
    <form action="{{ url_for('views.upload_file') }}" method="post" enctype="multipart/form-data">
        <input type="file" name="file" id="file">
        <input type="submit" value="Enviar">
    </form>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <a  href="https://icons8.com/icon/GtCWRmkr5I2V/robo">Robo</a> icon by <a href="https://icons8.com">Icons8</a> -->
    <link rel="styleesheet" href="{{ url_for('static', filename='style.css') }}" >
    <title>{% block title %}{% endblock %}</title>
</head>
<!-- Nota, qualquer atualização em css front resulta Control C + V cascata para todos HTML, para de esquecer por favor.  -->
<style>
    * {
        font-family: Arial, Helvetica, sans-serif;
    }

    a {
        position: relative;
        text-decoration: none;
        color: #91A663;
    }

    body {
        background-color: #262223;
        color: white;
    }

    .container {
        max-width: 385px;
        margin-top: 25px;
        margin: auto;
    }

    .login {
        margin: 15px;
        background-color: #ffffff13;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(255, 0, 0, 0.014);
    }

    form {
        padding: 15px;
    }

    header {
        margin-bottom: 25px;
    }

    header picture {
        width: 100%;
    }

    footer {
        margin-top: 20vh;
        text-align: center;
        padding: 15px;
    }

    article {
        display: inline-block;
        max-width: 300px;
    }

    section {
        display: block;
        position: relative;
        text-align: center;
    }

    section#updates {
        margin: auto;
        max-width: 400px;
    }

    section#updates img {
        display: block;
        max-width: 85px;
        margin: auto;
    }

    section p {
        max-width: 800px;
        margin: auto;
        padding: 5px;
    }

    section#comunidade img {
        max-width: 285px;
    }

    section#config {
        border-bottom: solid white 2px;
    }

    label {
        padding: 10px;
    }

    button#deVoltaAoTopo {
        position: fixed;
        bottom: 0;
        right: 0;
    }

    button#deVoltaAoTopo img {
        max-width: 65px;
    }

    button#deVoltaAoTopo a {
        position: absolute;
    }

    #newpage img {
        max-width: 185px;
    }

    #newpageimgdois img {
        max-width: 50px;
    }

    #taskList img {
        float: right;
        max-width: 300px;
    }

    #taskList div {
        margin: auto;
        max-width: 400px;
        padding: 15px;
    }

    #diario img {
        max-width: 200px;
    }

    #listaDeLeituras img {
        max-width: 300px;
    }

    #listaDeLeituras h2>img {
        max-width: 50px;
    }

    #addAPage img {
        max-width: 85px;
    }

    #teamSpace img {
        max-width: 185px;
    }

    #templates img {
        max-width: 285px;
    }

    #import img {
        max-width: 285px;
    }

    #trash img {
        max-width: 285px;
    }

    section img {
        transition-duration: 1s;
        transition-property: transform;
        transition-timing-function: ease-in-out;
        transform-origin: 50% 50%;
    }

    img:hover {
        transform: translate(-10px, 0);
        transition-duration: 3s;
    }

    button {
        margin: 15px;
        border-radius: 25px;
    }

    ul li {
        display: inline-block;
        list-style: none;
        margin: 15px;
        padding: 10px;
        border-radius: 15px;
        border: 1px solid gray;
    }

    nav {
        color: #fff;
        max-width: 200px;
    }

    nav ul {
        padding: 25px;
        border-right: solid 1px gray;
        display: none;
    }

    nav ul li {
        list-style: none;
    }

    nav ul li a {
        text-decoration: none;
        color: #fff;
    }

    nav:hover ul {
        display: block;

    }

    div#menuTop {
        display: flex;
    }

    div#menuTop p {
        border: solid gray 1px;
        border-radius: 15px;
        padding: 5px;
        margin: 10px;
    }

    input {
        max-width: 400px;
        font-size: 16px;
        border-radius: 25px;
        padding: 5px;
    }

    #input img {
        max-width: 35px;
    }

    picture#setasDuplas img {
        display: block;
        margin-top: 15px;
        width: 35px;
    }

    #esteira img {
        display: block;
        width: 55px;
    }

    #first img {
        float: right;
        max-width: 150px;
    }

    #logoZapSelling img {
        display: block;
        margin: auto;
        max-width: 120px;
        border-radius: 360px;
    }

    section#addAPage div {
        margin: 25px;
        margin-top: 15px;
        border: solid gray 2px;
        padding: 10px;
        border-radius: 15px;
    }

    li {
        list-style: none;
    }

    div#pop li {
        margin: 15px;
        padding: 15px;
        text-align: center;
        max-width: 285px;
        border: 2px solid gray;
        border-radius: 15px;
    }

    div#comunidade2 {
        display: flex;
        margin: 15px;
        border-top: 1px solid gray;
        border-bottom: 1px solid gray;
        padding: 15px;
    }

    div#comunidade2 img {
        display: block;
        max-width: 85px;
    }

    picture#feed img {
        display: block;
        margin: auto;
        max-width: 900px;
        border-radius: 15px;
    }

    picture img#setaDireitaMultimidia {
        float: right;
    }

    picture#desenhoDeUmBancoDeBadosRoxo img {
        display: block;
        max-width: 155px;
        margin: auto;
        border-radius: 10px;
    }

    div.tGatilho {
        max-width: 500px;
        margin: auto;
        margin-bottom: 15px;
    }

    .tGatilho {
        display: flex;
        margin: auto;
        text-align: center;
        border: solid gray 2px;
        border-radius: 15px;
        padding: 10px;
    }

    section#configurações {
        border: solid 2px gray;
        border-radius: 15px;
        max-width: 500px;
        margin: auto;
    }

    section#configurações p {
        padding: 15px;
        border-top: 1px solid gray;
        text-align: justify;
    }

    .flex {
        display: flex;
    }

    .flex div {
        margin: 15px;
    }

    .flex input {
        margin: 15px;
    }
</style>

<body>
    <header>
        <div id="menuTop">
            <nav>
                <picture id="setasDuplas">
                    <img src="{{ url_for('static', filename='setas-duplas-para-baixo.png') }}" alt="">
                </picture>
                <ul>
                    <li>
                        <a href="/help">Ajuda
                        </a>
                    </li>
                    <li>
                        
                        <a href="/comunidade">
                            Comunidade
                        </a>
                    </li>
                    <li>
                        <a href="/configuracao">
                            Configuração
                        </a>
                    </li>
                    <li>
                        <a href="/exemplo2">
                            Lixo Temporario
                        </a>
                    </li>
                    <li>
                        <a href="/funil">
                            Modelos
                        </a>
                    </li>
                    <li>
                        <a href="/perfil">
                            Minha Conta
                        </a>
                    </li>
                    <li>
                        <a href="/logout">
                            Sair
                        </a>
                    </li>
                  

                </ul>
            </nav>
            <label id="input" for="">
                <img src="{{ url_for('static', filename='lupa.png') }}" alt="">
                <input type="text" name="" id="" placeholder="Pesquisa">
            </label>
            <a href="/home">
                <p>
                    inicio
                </p>
            </a>
            <a href="/auto_message">
                <p>
                    Upload de Arquivos
                </p>
            </a>
            <a href="https://api.whatsapp.com/send?phone=5519986030166&text=TESTE%0ASuporte%20!!!%0ABom%20dia,%20%0ATenho%20um%20grave%20problema%20com%20a%20plataforma%20e%20preciso%20apoio%20imediato."
                target="_blank">
                <p>
                    SUPORTE
                </p>
            </a>
            <a href="{{ url_for('views.excluir_conta') }}">Excluir conta</a>

        </div>
        <picture id="logoZapSelling">
            <img src="{{ url_for('static', filename='logo.jpeg') }}" alt="">
        </picture>
    </header>
    <div>{% block content %} {% endblock %}</div>
    <footer>
        <p>
            © 2023 - Todos os direitos reservados by - <a style="margin-left: 5px;"
                href="https://www.instagram.com/ryanferreira_019/" target="_blank">RYAN
                FERREIRA</a> & <a href="https://www.instagram.com/pk_digital_products/" target="_blank">PK DIGITAL
                PRODUCTS</a>
        </p>
    </footer>
</body>







  

website/templates/comunidade.html
{% extends 'base.html' %}

{% block title %} ZapSelling {% endblock %}

{% block content %}
<header>

</header>
<!-- Área dos membros -->
<section id="comunidade">

    <form method="POST">
        <textarea name="text" id="text" class="form-control"></textarea>
        <br>
        <div align="center">
            <button type="submit" class="btn btn-lg btn-primary">Postar</button>
        </div>
    </form>
    <h1 align="center">Feed de notícias</h1>
    <div id="posts">
        {% for post in posts %}
        <div class="card border-dark">
            <div class="card-header d-flex justify-content-between align-items-center">
                <a href="/posts/{{ post.user.nome }}">{{ post.user.nome }}</a>
                {% if user.id == post.author %}
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-bs-toggle="dropdown">
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('views.delete_post', id=post.id) }}" class="dropdown-item">Excluir</a>
                        </li>
                    </ul>
                </div>
                {% endif %}
            </div>
            <div class="card-body">
                <div class="card-text">{{ post.text }}</div>
            </div>
            <div class="card-footer text-muted">{{ post.date_created }}</div>
        </div>
        <br>
        {% endfor %}
    </div>
    {% endblock %}

website/templates/configuracao.html
{% extends 'base.html' %} {% block title %} ZapSelling {% endblock%}
{% block content %}


{% endblock %}

website/templates/excluir_conta.html
{% extends 'base.html' %}
{% block title %} Minhas Mensagens {% endblock %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Excluir Conta</title>
</head>
<body>
    <h1>Tem certeza de que deseja excluir sua conta?</h1>
    <form action="{{ url_for('views.excluir_conta') }}" method="post">
        <input type="submit" value="Confirmar Exclusão">
    </form>
</body>
</html>

{% endblock %}

website/templates/funil.html
{% extends 'base.html' %}
{% block title %}Funil{% endblock %}
{% block content %}

<h1>Funil</h1>

<form action="{{ url_for('views.funil') }}" method="post" enctype="multipart/form-data">
    <label for="conteudo">Conteúdo:</label>
    <textarea name="conteudo" id="conteudo" required></textarea>
    <label for="arquivo">Arquivo:</label>
    <select name="arquivo" id="arquivo">
        <option value="">Selecione um arquivo</option>
        {% for arquivo in arquivos %}
        <option value="{{ arquivo.id }}">{{ arquivo.nome }}</option>
        {% endfor %}
    </select>
    <input type="submit" name="enviar" value="Enviar">
    <input type="submit" name="salvar" value="Salvar">
</form>

<h2>Mensagens Salvas</h2>
<ul>
    {% for mensagem in mensagens %}
    <li>{{ mensagem.conteudo }}
        <form action="{{ url_for('views.funil') }}" method="post">
            <input type="hidden" name="mensagem_id" value="{{ mensagem.id }}">
            <input type="submit" name="excluir" value="Excluir">
        </form>
    </li>
    {% endfor %}
</ul>

{% endblock %}

website/templates/help.html
{% extends 'base.html' %} {% block title %} ZapSelling {% endblock%}

{% block content %}




<!-- Essa parte é esclusiva para o 'Guia', atenção na alteração de commit -->
<section id="addAPage">
    <h1 style="text-align: justify; background-color: rgb(14, 92, 11);">
        Guia do usuário (Passo a passo de como utilizar a ferramenta)
    </h1>
    <h1>
        Vai até o Menu e escolha a opção 'Gerenciador de Leads'.
    </h1>
    <h2>
        Selecione uma das opções, alimente os gatilhos de resposta.
    </h2>
    <h2>
        Agora é simples, começe a desenvolver o seu script automatizado da forma que prefierir.
    </h2>
    <h2>
        <strong>Inicio</strong>
    </h2>
    <picture id="star">
        <img src="{{ url_for('static', filename='comecar.png') }}" alt="">
    </picture>
    <picture id="clieteChega">
        <img src="{{ url_for('static', filename='clienteChega.png') }}" alt="">
    </picture>
    <h2>
        **1. ** Conheça seu público-alvo
    </h2>
    <p>
        Antes de começar a vender, é importante conhecer bem o seu público-alvo.
    </p>
    <p>
        Quem são as pessoas que você quer atingir?
    </p>
    <p>
        Quais são suas necessidades e interesses? Quais são as suas dores e desejos?
    </p>
    <p>
        Entendendo seu público-alvo, você poderá criar mensagens e ofertas mais direcionadas, aumentando as
        chances de sucesso nas vendas.
    </p>
</section>
<picture id="setasMultimidia">
    <a href="#">
        <img id="setaEsquedaMultimidia" src="{{ url_for('static', filename='duas-setas-para-a-esquerda (1).png') }}"
            alt="">
    </a>
    <a href="guai2.html">
        <img id="setaDireitaMultimidia" src="{{ url_for('static', filename='avanco-rapido.png') }}" alt="">
    </a>
</picture>
</body>

</html>
{% endblock %}

website/templates/home.html
{% extends 'base.html' %} {% block title %} ZapSelling {% endblock%} {% block content %} {% endblock %}

website/templates/lixo.html
{% extends 'base.html' %} 
{% block title %} ZapSelling {% endblock %} 
{% block content %} 

<form action="{{ url_for('views.lixo_temporario') }}" method="post">
    <label for="garbage">Selecione o lixo temporário:</label>
    <select name="garbage" id="garbage">
        {% for item in garbage_list %}
        <option value="{{ item.id }}">{{ item.nome }}</option>
        {% endfor %}
    </select>
    <input type="hidden" name="item_type" id="item_type" value="arquivo"> 
    <button type="submit">Resgatar</button>
</form>

{% endblock %}

website/templates/perfil.html
{% extends 'base.html' %} {% block title %} ZapSelling/{{nome}} {% endblock%}




{% block content %}

html


{% endblock %}

website/templates/visualizar_arquivo.html
{% extends 'base.html' %}

{% block content %}
    <h1>Conteúdo do Arquivo: {{ arquivo.nome }}</h1>
    {% if arquivo.tipo == 'png' or arquivo.tipo == 'jpg' or arquivo.tipo == 'jpeg' or arquivo.tipo == 'gif' %}
        <img src="data:image/{{ arquivo.tipo }};base64,{{ arquivo.conteudo_base64 }}" alt="{{ arquivo.nome }}">
    {% elif arquivo.tipo == 'mp3' %}
        <audio controls>
            <source src="data:audio/mp3;base64,{{ arquivo.conteudo_base64 }}" type="audio/mp3">
            Seu navegador não suporta o elemento de áudio.
        </audio>
    {% elif arquivo.tipo == 'mp4' %}
        <video controls>
            <source src="data:video/mp4;base64,{{ arquivo.conteudo_base64 }}" type="video/mp4">
            Seu navegador não suporta o elemento de vídeo.
        </video>
    {% elif arquivo.tipo == 'doc' %}
        <!-- Exibir arquivo DOC -->
        <!-- Você pode adicionar um link de download para o arquivo DOC, se desejar -->
        <a href="data:application/msword;base64,{{ arquivo.conteudo_base64 }}" download="{{ arquivo.nome }}">Baixar {{ arquivo.nome }}</a>
    {% elif arquivo.tipo == 'xlsx' %}
        <!-- Exibir arquivo XLSX -->
        <!-- Você pode adicionar um link de download para o arquivo XLSX, se desejar -->
        <a href="data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,{{ arquivo.conteudo_base64 }}" download="{{ arquivo.nome }}">Baixar {{ arquivo.nome }}</a>
    {% elif arquivo.tipo == 'pdf' %}
        <!-- Exibir arquivo PDF -->
        <embed src="data:application/pdf;base64,{{ arquivo.conteudo_base64 }}" type="application/pdf" width="100%" height="600px" />
    {% elif arquivo.tipo == 'txt' %}
        <!-- Exibir arquivo de texto -->
        <pre>{{ arquivo.conteudo_base64|unescape }}</pre>
    {% else %}
        <p>Tipo de arquivo não suportado.</p>
    {% endif %}
{% endblock %}